### PR TITLE
Support Printing Text

### PR DESCRIPTION
**Pull request by sstiglitz**
Hey, thank you for putting all this together, what a great idea.

There is #42 which talked about the idea of printing text, but nothing was implemented and the linked PR isn't the solve.

What I would like is I could issue a command like 

```
python print.py --message "Its Hack 'o Clock"
```

And it would print something very close to the image in the repo.

With this, my hope is to create a silly shopping list creator. Glue a magnet to the back of this badboy, pop it on the fridge, then send a text/email/tweet, "Buy more peanut butter". Tear it off on your way to the store. Voila, shopping list creator.

### CODE REVIEW

**Comment by sstiglitz** [comment]
I'm stuck and I could use a hand.

I believe my only option is to give the catprinter a set of lattice points (x,y coords telling the printer where to print in 2d space). So I need to take a string as input, and produce a bunch of x,y coords that represent the text.

Sounds hard, I wanted to do a couple more things with my weekend besides making some type of algo for this. Someone has to have already done this before, right? 

If you know of anything, or have any potential leads you can throw my way, I'm all ears.

**Comment by rbaron** [comment]
Hey @sstiglitz thanks for getting start on the PR and on the discussion. I think we have some options. From the top of my head:

1. Print one string per line. Users are supposed to ensure each line fits the max width. You can add a left margin with some whitespace character and vertical spaces with empty lines. This is the simplest solution I can think of. We can even go one step further and input a text file with the exact formatting we want and have the Python script render it into lines with some monospace font
2. We can come up with some "rich text" representation. For example some structured text in which we can encode something like:
```
text_to_print: [{
  x: 3,
  y: 4,
  string: "hello, ",
  // Optionally, we can get increasingly as fancy as we want:
  text_size: 2,
  text_weight: "bold",
  font: "serif",
  align: "center"
}, {
  x: 0,
  y: 6,
  string: "world"
}]
```

Then we would have to teach the Python script how to render this into an image. We already have OpenCV as a dependency, so we could use that.

3. We can take this idea to the limit and use HTML as a (drum roll) markup language. We can go full insane and call out [Selenium](https://www.selenium.dev/) from Python to headlessly render the HTML and hand over an screenshot for us. It's a wild idea, but it would be pretty awesome and flexible I think. We would have ultimate freedom for content form, at the expense of a huge (hidden? cross-platform-nightmare? awesome?) complexity.

In fact, the app that was reverse engineered apparently has already some notion of HTML. I think there might be some capacity of text printing, but it would need more investigation (I suspect it's rendered into an image and then sent to the printer). These are the notes I took when I was taking a look at it, if someone wants to dig in:

```
# Flow

PrintPreviewActivity:
	printBrn()
		some encryption / hashing going on?
		calls this.mMyHandler.sendEmptyMessage(5);

	myHandler:
    case 5:
			PrintPreviewActivity.this.PrintBitmap();

	PrintBitMap()
		PrintDataUtils.getInstance().setTextSpeed(intValue);
		this.list.clear()
		Switches between media types
			if (Code.QUESTION_HTML.equals(this.type) || Code.XUEKEWANG_HTML.equals(this.type)) {
			} else if (this.activityType.equals(Code.HTMLTYPE)) {
			} else if (this.activityType.equals(Code.OFFICE_PRINT)) {
			} else if (this.activityType.equals(Code.HTMLTYPE)) {
			// I believe this is the "if photo" path
			} else {
				while (i < PrintPreviewActivity.this.printList.size()) {
					PrintBean printBean = (PrintBean) PrintPreviewActivity.this.printList.get(i);
					printBean.setBitmap(bitmap);
				}
				PrintPreviewActivity.this.list.addAll(PrintPreviewActivity.this.printList);
        PrintPreviewActivity.this.mMyHandler.sendEmptyMessage(4);
```

**Comment by sstiglitz** [comment]
Alright should be good to go.

I wanted to go with option 3, but I was running into too many issues when trying to run from a headless server.

**Comment by jo-m** [comment]
In my Golang port, I do this via markdown and wkhtmltopdf: https://github.com/jo-m/mdcatprint

**Pull request closed without merging**
